export const USER_LOGIN="LOGIN_PAGE"
export const USER_USERNAME="GET_USERNAME"
export const USER_PASSWORD="GET_PASSWORD"
export const VALID_LOGIN="VALID_LOGIN"
export const GET_WEATHER = "GET_WEATHER"
export const GET_CITY = "GET_CITY" 